apiVersion: apps/v1
kind: Deployment
metadata:
  name: ep1f
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ep1f
  template:
    metadata:
      labels:
        app: ep1f
    spec:
      containers:
        - name: ep1f
          image: huzi0906/ep1f
          ports:
            - containerPort: 80
              hostPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ep1f
spec:
  selector:
    app: ep1f
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
