apiVersion: apps/v1
kind: Deployment
metadata:
  name: ep5b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ep5b
  template:
    metadata:
      labels:
        app: ep5b
    spec:
      containers:
        - name: ep5b
          image: huzi0906/ep5b
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_DB_URL
              value: mongodb://ep5db.production.svc.cluster.local:27017
---
apiVersion: v1
kind: Service
metadata:
  name: ep5b
spec:
  selector:
    app: ep5b
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
