apiVersion: apps/v1
kind: Deployment
metadata:
  name: ep5db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ep5db
  template:
    metadata:
      labels:
        app: ep5db
    spec:
      containers:
        - name: ep5db
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: ep5db-data
              mountPath: /data/db
      volumes:
        - name: ep5db-data
          persistentVolumeClaim:
            claimName: ep5db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ep5db
spec:
  selector:
    app: ep5db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
